spring:
  application:
    name: UniAttendanceSystem

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cs544-attendance
    hikari:
      maximum-pool-size: 10

  data:
    jdbc:
      dialect: mysql
