spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cs544-bank
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create