spring:
  application:
    name: react-backend

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true


  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/react-backend
  sql:
    init:
      mode: always


