spring:
  application:
    name: Lab5PartA

  datasource:
    url: jdbc:mysql://localhost:3306/cs544-examples
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    jdbc:
      dialect: mysql
