spring:
  application:
    name: Lab6PartB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        type: trace
    show-sql: true


  datasource:
    url: jdbc:mysql://localhost:3306/cs544-examples
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 10
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#        type:
#          descriptor:
#            sql:
#              BasicBinder: trace



